#服务配置
server:
  port: 9002
  address: localhost
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true

  # redis 服务配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
jwt:
  config:
    salt: ihrm_system
    expireTime: 10800000 # 3小时失效



#服务注册中心实例的主机名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
